baseURL = "https://teosibileau.github.io/"
title = "Teófilo Sibileau"
languageCode = "en"
theme = "HugoTeX"
enableInlineShortcodes = true

[Params]
  lightmode = true

[Params.author]
  name = "Teo Sibileau"
  abstract = "Python Backend Developer"
  linkedin = "https://www.linkedin.com/in/teofilo-sibileau-18800058/"
  github = "https://github.com/teosibileau/"

[markup.goldmark.renderer]
  unsafe = true

[markup.goldmark.parser.attribute]
  block = true

[markup.highlight]
  style = "monokai"
