site_name: Teo Sibileau
theme:
  name: material
plugins:
  - search
  - macros:
      include_dir: partials
  - encryptcontent:
        password_inventory:
          secret:
            teo: 'secret'
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      use_pygments: True
  - toc:
      permalink: True
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/icons